name: kakao-chat-ci
run-name: Deploy by @${{ github.actor }} 

on: 
    push: 
        branches: 
            - main
            - develop
    pull_request:
        types: [review_requested, opened, reopened, ready_for_review]
    pull_request_review:
        types: [submitted, edited, dismissed]

jobs:
    build-and-notify:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
              
            - name: Install dependencies
              run: npm install

            - name: Determine event type and trigger action at Windows
              if: runner.os == 'Windows' 
              run: |
                if (${{github.event_name}} == 'push') {}
                  echo "event_name=${{ github.event_name }}" >> $env:GITHUB_OUTPUT
                  echo "username=${{ github.event.head_commit.author.username }}" >> $env:GITHUB_OUTPUT
                  echo "actor=${{ github.actor }}" >> $env:GITHUB_OUTPUT
                  echo "commit_message=${{ github.event.head_commit.message }}" >> $env:GITHUB_OUTPUT
                } elseif (${{github.event_name}} == 'pull_request') {
                  echo "event_name=${{ github.event_name }}" >> $env:GITHUB_OUTPUT
                  echo "username=${{ github.event.pull_request.user.login }}" >> $env:GITHUB_OUTPUT
                  echo "actor=${{ github.actor }}" >> $env:GITHUB_OUTPUT
                  echo "commit_message=${{ github.event.pull_request.title }}" >> $env:GITHUB_OUTPUT
                }
              id: determine_event_type_windows
            
            - name: Get Event Name from Windows
              if: runner.os == 'Windows'
              run: |
                echo "event_name : ${{ steps.determine_event_type_windows.outputs.event_name }}"
                echo "username : ${{ steps.determine_event_type_windows.outputs.username }}"
                echo "actor : ${{ steps.determine_event_type_windows.outputs.actor }}"
                echo "commit_message : ${{ steps.determine_event_type_windows.outputs.commit_message }}"

            - name: Determine event type and trigger action at macOS
              if: runner.os == 'macOS' 
              run: |
                if [ ${{github.event_name}} == 'push' ]; then
                  echo `TITLE=[${{github.actor}}] ${{ github.event_name }}` >> $GITHUB_OUTPUT
                  echo "DESC=${{ github.event.head_commit.message }}" >> $GITHUB_OUTPUT
                elif [ ${{github.event_name}} == 'pull_request' ]; then
                  echo `TITLE=[${{github.actor}}] ${{ github.event_name }}` >> $GITHUB_OUTPUT
                  echo "DESC=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
                elif [ ${{github.event_name}} == 'pull_request_review' ]; then
                  echo `TITLE=[${{github.actor}}] ${{ github.event_name }}` >> $GITHUB_OUTPUT
                  echo "DESC=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
                fi
              id: determine_event_type_mac

            - name: Get event type
              if: runner.os == 'macOS'
              run: |
                echo "TITLE : ${{ steps.determine_event_type_mac.outputs.TITLE }}"
                echo "DESC : ${{ steps.determine_event_type_mac.outputs.DESC }}"     

                
