name: kakao-chat-ci
run-name: Deploy by @${{ github.actor }} 

on: 
    push: 
        branches: 
            - main
            - develop
    pull_request:
        types: [review_requested]
    pull_request_review:
        types: [submitted, edited, dismissed]

jobs:
    build-and-notify:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Determine event type and trigger action
              if: github.event_name == 'push'
              run: |
                if [${{github.event_name}} == 'push']; then
                  echo "event_name=${{ github.event_name }}" >> $env:GITHUB_OUTPUT
                  echo "username=${{ github.event.head_commit.author.username }}" >> $env:GITHUB_OUTPUT
                  echo "actor=${{ github.actor }}" >> $env:GITHUB_OUTPUT
                  echo "commit_message=${{ github.event.head_commit.message }}" >> $env:GITHUB_OUTPUT
                elif [${{github.event_name}} == 'pull_request']; then
                  echo "event_name=${{ github.event_name }}" >> $env:GITHUB_OUTPUT
                  echo "username=${{ github.event.pull_request.user.login }}" >> $env:GITHUB_OUTPUT
                  echo "actor=${{ github.actor }}" >> $env:GITHUB_OUTPUT
                  echo "commit_message=${{ github.event.pull_request.title }}" >> $env:GITHUB_OUTPUT
                fi
              id: determine_event_type
            
            - name: Get Event Name
              run: |
                echo "event_name : ${{ steps.determine_event_type.outputs.event_name }}"
                echo "username : ${{ steps.determine_event_type.outputs.username }}"
                echo "actor : ${{ steps.determine_event_type.outputs.actor }}"
                echo "commit_message : ${{ steps.determine_event_type.outputs.commit_message }}"


