name: kakao-chat-ci
run-name: Deploy by @${{ github.actor }} 

on: 
    push: 
        branches: 
            - main
            - develop
    pull_request:
        types: [review_requested]
    pull_request_review:
        types: [submitted, edited, dismissed]

jobs:
    build-and-notify:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Set up node
              uses: actions/setup-node@v3
              with:
                node-version: 18
            
            - name: Install dependencies
              run: npm install

            - name: Determine event type and trigger action
              run: |
                EVENT_NAME="${{ github.event_name }}"
                if [[ "${{ github.event_name }}" == "push" ]]; then
                  AUTHOR="${{ github.event.head_commit.author.username }}"
                  DESC="${{ github.event.head_commit.message }}"
                elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
                  if [[ "${{ github.event.action }}" == "opened" ]]; then
                    AUTHOR="${{ github.event.pull_request.user.login }}"
                    DESC="${{ github.event.pull_request.title }}"
                  elif [[ "${{ github.event.pull_request.draft }}" == "false" && "${{ github.event.action }}" == "synchronize" ]]; then
                    AUTHOR="${{ github.event.pull_request.user.login }}"
                    DESC="${{ github.event.pull_request.title }}"
                  fi
                elif [[ "${{ github.event_name }}" == "pull_request_review" ]]; then
                  AUTHOR="${{ github.event.review.user.login }}"
                  DESC="${{ github.event.review.body }}"
                elif [[ "${{ github.event_name }}" == "pull_request_review" && "${{ github.event.review.state }}" == "approved" ]]; then
                  AUTHOR="${{ github.event.review.user.login }}"
                  DESC="${{ github.event.pull_request.title }}"
                fi
                TITLE="[$EVENT_NAME] $AUTHOR"
                echo "TITLE=$TITLE"
                echo "DESC=$DESC"
            

    
