name: kakao-chat-ci
run-name: Deploy by @${{ github.actor }} 

on: 
    push: 
        branches: 
            - main
            - develop
    pull_request:
        types: [review_requested]
    pull_request_review:
        types: [submitted, edited, dismissed]

jobs:
    build-and-notify:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Determine event type and trigger action
              run: |
                echo "event_name=${{ github.event_name }}" >> $GITHUB_OUTPUT
              id: determine_event_type
            
            - name: Get Event Name
              run: |
                echo "GITHUB_EVENT_NAME=${{ steps.determine_event_type.outputs.event_name }}"

    
